entrada = int(input("Qual tabuada vc quer de 1 a 9? "))

while (entrada != 0) and (entrada < 10) :
    multiplica1 = entrada * 1
    multiplica2 = entrada * 2
    multiplica3 = entrada * 3
    multiplica4 = entrada * 4
    multiplica5 = entrada * 5
    multiplica6 = entrada * 6
    multiplica7 = entrada * 7
    multiplica8 = entrada * 8
    multiplica9 = entrada * 9
    multiplica10 = entrada * 10
    print("%d x %d = %d " %(entrada, 1, multiplica1),
        "%d x %d = %d " %(entrada, 2, multiplica2),
        "%d x %d = %d " %(entrada, 3, multiplica3),
        "%d x %d = %d " %(entrada, 4, multiplica4),
        "%d x %d = %d " %(entrada, 5, multiplica5),
        "%d x %d = %d " %(entrada, 6, multiplica6),
        "%d x %d = %d " %(entrada, 7, multiplica7),
        "%d x %d = %d " %(entrada, 8, multiplica8),
        "%d x %d = %d " %(entrada, 9, multiplica9),
        "%d x %d = %d " %(entrada, 10, multiplica10))
    entrada = int(input("Qual tabuada vc quer de 1 a 9? digite 0 para sair "))
    multiplica1 = entrada * 1
    multiplica2 = entrada * 2
    multiplica3 = entrada * 3
    multiplica4 = entrada * 4
    multiplica5 = entrada * 5
    multiplica6 = entrada * 6
    multiplica7 = entrada * 7
    multiplica8 = entrada * 8
    multiplica9 = entrada * 9
    multiplica10 = entrada * 10
